Repository chubchubsancho/ansible-pi-hole, pull requests merged in 2022-08, with the labels that each got.

#11 Restart pi-hole FTL when local DNS records change
  tasks/configure.yml
Labels: enhancement, bump:patch

#13 fix(test): remove old OS
  .github/workflows/test.yaml
Labels: bug

#12 feat: add rate limit support
  README.md
  templates/etc/pihole/pihole-FTL.conf.j2
Labels: bump:minor
